from django.urls import path, include  # Import path for URL patterns and include to include other URL configs
from rest_framework.routers import DefaultRouter  # Import DRF's DefaultRouter for automatic routing of ViewSets
from .views import *  # Import the ViewSets

# Create a router instance for automatic URL routing
router = DefaultRouter()
router.register("customers", CustomerViewSet)  # Register CustomerViewSet with the 'customers' prefix
router.register("orders", OrderViewSet)  # Register OrderViewSet with the 'orders' prefix
router.register("tracking-events", OrderTrackingEventViewSet)  # Register OrderTrackingEventViewSet with 'tracking-events' prefix

# Include all router URLs in the urlpatterns
urlpatterns = [
    path("", include(router.urls)),  # Include all URLs generated by the router
]
